server:
  port: 9000

orchestrator:
  pipelines:

    - name: consumption-pipeline
      description: "This pipeline uses an LDES client to read an existing LDES (both replicate and synchronize) and send the members as N-quads to a message sink which stores the members in a database."
      input:
        name: be.vlaanderen.informatievlaanderen.ldes.ldi.client.LdioLdesClient
        config:
          url: http://${HOSTNAME}:8080/observations/by-time?year=2023&month=11&day=23
      transformers:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.VersionMaterialiser
      outputs:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpOut
          config:
            endpoint: http://${HOSTNAME}:9003/member
            rdf-writer:
              content-type: application/n-quads
