version: '3.3'
volumes:
  nifi-database-repository:
  nifi-flowfile-repository:
  nifi-content-repository:
  nifi-provenance-repository:
  nifi-state:
  nifi-logs:
  nifi-nars:
  nifi-conf:
  geo-db-data:

networks:
  front-tier:
    driver: bridgea
  back-tier:
    driver: bridge
  crashcourse:
    name: crashcourse_network
services:
  ldes-mongodb:
    container_name: crashcourse_ldes-mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - crashcourse
      
  nifi:
    container_name: crashcourse_ldes-workbench-nifi
    image: ldes/ldi-workbench-nifi:2.3.0-SNAPSHOT
    restart: unless-stopped
    ports:
      # HTTPS
      - 8443:8443/tcp
    volumes:
      - ./nifi-extensions:/opt/nifi/nifi-current/extensions
    environment:
      - NIFI_UI_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=admin123456789
      - NIFI_WORKFLOW_LISTEN_PORT=9005
      - NIFI_JVM_HEAP_INIT=8g
      - NIFI_JVM_HEAP_MAX=8g
    networks:
      - crashcourse
  graphdb:
    image: ontotext/graphdb:10.4.2
    container_name: crashcourse_graphdb
    ports:
      # HTTP
      - 7200:7200
    networks:
      - crashcourse

  ldio-workbench:
    container_name: crashcourse_ldio-workbench
    image: ldes/ldi-orchestrator:2.5.1-SNAPSHOT
    environment:
      - SIS_DATA=/tmp
      - JAVA_TOOL_OPTIONS="-Xmx1280m"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9006/actuator/health"]
    volumes:
      - ./workbench/config.yml:/ldio/application.yml:ro
      - ./workbench/sparql:/ldio/sparql:ro
      - ./workbench/jsonld:/ldio/jsonld:ro
      - ./workbench/tmp/epsg:/tmp/Databases:rw
    ports:
      - 8081:8080
    networks:
      - crashcourse
    profiles:
      - delay-started


  ldes-server:
    container_name: crashcourse_ldes-server
    image: ldes/ldes-server:2.14.0-SNAPSHOT
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://ldes-mongodb/minimal-server
      - LDESSERVER_HOSTNAME=http://localhost:9003
      - SIS_DATA=/tmp
    volumes:
      - ./server/config.yml:/application.yml:ro
      - ./server/tmp/epsg:/tmp/Databases:rw
    ports:
      - 8080:8080
    networks:
      - crashcourse
    depends_on:
      - ldes-mongodb
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldes-server:8080/actuator/health"]
      
  dba:
    image: dpage/pgadmin4:latest
    container_name: crashcourse-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ldes@ldes.be
      PGADMIN_DEFAULT_PASSWORD: ldes
    ports:
      - 8001:80
    depends_on:
      - postgis
    networks:
      - crashcourse

  postgis:
    build: ./docker/postgres
    container_name: crashcourse-postgis
    environment:
      POSTGRES_DB: crashcourse
      POSTGRES_USER: ldes
      POSTGRES_PASSWORD: ldes
    volumes:
        - geo-db-data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - crashcourse