server:
  port: 8080
orchestrator:
  pipelines:

    - name: traffic-pipeline
      description: "Ingests Telraam HTTP messagge, converts to JSON-LD, converts to WKT, converts to intermediate format, converts to OSLO model, creates versions and posts HTTP message to LDES server."
      input:
        name: Ldio:HttpIn
        adapter:
          name: Ldio:JsonToLdAdapter
          config:
            core-context: file:///ldio/jsonld/traffic.jsonld
      transformers:
        - name: Ldio:GeoJsonToWktTransformer
        - name: Ldio:SparqlConstructTransformer
          config:
            query: ./sparql/traffic.to-observation.rq
        - name: Ldio:SparqlConstructTransformer
          config:
            query: ./sparql/observation.to-oslo.rq
        - name: Ldio:VersionObjectCreator
          config:
            member-type: https://data.vlaanderen.be/ns/verkeersmetingen#Verkeersmeting
            delimiter: "-"
            date-observed-property: "<http://def.isotc211.org/iso19156/2011/Observation#OM_Observation.phenomenonTime>/<http://www.w3.org/2006/time#hasBeginning>/<http://www.w3.org/2006/time#inXSDDateTimeStamp>"
            generatedAt-property: http://www.w3.org/ns/prov#generatedAtTime
            versionOf-property: http://purl.org/dc/terms/isVersionOf
      outputs:
        - name: Ldio:HttpOut
          config:
            endpoint: http://ldes-server:8080/ldes/observations
            content-type: application/n-quads

spring:
  codec:
    max-in-memory-size: 10MB

logging:
  level:
    root: WARN
    be.vlaanderen.informatievlaanderen.ldes.ldio.Application: INFO